FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# The port the Flask server will run on inside the container
EXPOSE 5056
CMD ["python", "main.py"]
